apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-honeycomb-ordermgr
spec:
  selector:
    matchLabels:
      app: saas-honeycomb-ordermgr
  replicas: 1
  template:
    metadata:
      labels:
        app: saas-honeycomb-ordermgr
    spec:
      containers:
      - name: saas-honeycomb-ordermgr
        image: hzhyvinskyi/saas-honeycomb-ordermgr:latest
        env:
        - name: APP_NAME
          value: saas-honeycomb-ordermgr
        - name: PORT
          value: "8091"
